### ISSUE TITLE
init is not a function

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers#1204]
Not sure if this a bug or not as can't reproduce but trying to understand why it would happen as it's an error that seems to crop up reasonably regularly.

The error I get is 

> Uncaught (in promise): TypeError: t.init is not a function
> TypeError: t.init is not a function

My angular service is as below

```
export class ApiService {
  private feathers: any;
  constructor(
    private http: HttpClient,
  ) {
    this.feathers = feathers(); // Error occurs here
    const restClient: Transport = rest(environment.host);

    this.feathers
      .configure(
        restClient.angularHttpClient(this.http, { HttpHeaders: HttpHeaders })
      ));
  }
}
```

**Comment by daffl** [comment]
This should be fixed via https://github.com/feathersjs/feathers/pull/1153 in `@feathersjs/feathers` v3.3.1 and later.

**Comment by dottodot** [comment]
I'm using `@feathersjs/client` 3.7.3

**Comment by dottodot** [comment]
And the api it's connecting to uses 3.3.1

**Comment by dottodot** [comment]
Look like the client doesn't have the same fix.

```
function createApplication() {
  var app = {}; // Mix in the base application

  Proto.mixin(Application, app);
  app.init();
  return app;
}
```

**Comment by daffl** [comment]
The `@feathersjs/client` version that has the fix is v3.7.8 (current latest)

**Comment by dottodot** [comment]
OK thanks, yarn normally picks up when an update is available, but hasn't done for this.

**Comment by daffl** [comment]
Maybe. We were only seeing this for `app.init` and the above fixed all errors that were Feathers related. It could be that whatever browser plugin or library causes affects other libraries as well.

**Comment by daffl** [comment]
Closing since I think the Feathers related issue should be fixed in the latest version.

**Comment by joacub** [comment]
the error is still, same error here on latest version on some circustances, not always

**Comment by dottodot** [comment]
Yeah I still get it on a regular basis, never have found the cause.

**Comment by joacub** [comment]
yes is very stranger, i got the error in some circustance is dificult to cathc the error i need put one event to catch this and addEventlistener('error')

**Comment by joacub** [comment]
im try to follow the bundle requires and aparently some index not exist for example on my bundle n(213) the index 213 not exist on any file

**Comment by daffl** [comment]
As I mentioned, it's usually some browser extension messing with built in JavaScript prototypes. Don't know what else can be done here other than #1153 unless someone can provide a reliably reproducible use case.

**Comment by joacub** [comment]
O have a day around of 150 weird about this so not is a small bug, I think this need a solution or change the init function to other name
