### ISSUE TITLE
TypeScript definitions for publish callback

### ISSUE THREAD

**Issue by deskoh** [feathersjs/feathers#1278]
Referencing following lines:
https://github.com/feathersjs/feathers/blob/9dd671301ae0463968ade0f6eb0c82356adcc89d/packages/transport-commons/src/channels/index.ts#L13

https://github.com/feathersjs/feathers/blob/9dd671301ae0463968ade0f6eb0c82356adcc89d/packages/transport-commons/src/channels/index.ts#L15

The callback should be a function that could return `null` as documented [here](https://docs.feathersjs.com/api/channels.html#publishing).

**Comment by daffl** [comment]
This has been fixed this weekend. It will be published with Feathers 4.

**Comment by deskoh** [comment]
Any timeline when Feathers 4 will be published?

**Comment by deskoh** [comment]
> This has been fixed this weekend. It will be published with Feathers 4.

Looking at the PR https://github.com/feathersjs/feathers/pull/1275 merge to master branch, the `callback` return type still does not include `Channel[] | void`

https://github.com/feathersjs/feathers/blob/2667d92efb087cfbe75f64e9ba5c787cec5eb260/packages/transport-commons/src/channels/index.ts#L13

https://github.com/feathersjs/feathers/blob/2667d92efb087cfbe75f64e9ba5c787cec5eb260/packages/transport-commons/src/channels/index.ts#L15

Unlike

https://github.com/feathersjs/feathers/blob/2667d92efb087cfbe75f64e9ba5c787cec5eb260/packages/transport-commons/src/channels/index.ts#L25

https://github.com/feathersjs/feathers/blob/2667d92efb087cfbe75f64e9ba5c787cec5eb260/packages/transport-commons/src/channels/index.ts#L28

Is there any other branch that contains the fix?

**Comment by deskoh** [comment]
Closed by https://github.com/feathersjs/feathers/pull/1396/
