### ISSUE TITLE
[v4] typscript project get error when create service

### ISSUE THREAD

**Issue by hunght** [feathersjs/feathers#1462]
### Steps to reproduce

1- generate app choose typescript
2- create service 
3- yarn start and get error:

 `node_modules/feathers-nedb/types/index.d.ts:8:10 - error TS2709: Cannot use namespace 'NeDB' as a type.

8   Model: NeDB;`

**Comment by daffl** [comment]
This has been fixed in https://github.com/feathersjs-ecosystem/feathers-nedb/pull/97. Make sure you install `feathers-nedb@5.0.1` or later.

**Comment by hunght** [comment]
![Screen Shot 2019-07-16 at 11 32 32 PM](https://user-images.githubusercontent.com/1697756/61312273-49155500-a822-11e9-8d1c-4bdae23608d4.png)
I still get this error when updated to feathers-nedb@5.0.1

**Comment by daffl** [comment]
Fixed in `@feathersjs/cli@4.0.0-pre.4`
